### PR TITLE
BKDeltaCalculator example

### PR DESCRIPTION
**Pull request by toulouse**
The original API was correct and fully functional. I added convenience methods to BKDelta to apply the insertions/deletions/movements.

@ide 

I actually think that with this, it's good enough to publish to CocoaPods as an honest-to-goodness CocoaPod.

### CODE REVIEW

**Comment by toulouse** [comment]
UITableView docs:

> If you want multiple rows moved, you can call this method repeatedly within a beginUpdates–endUpdates block.

UICollectionView docs:

> You can also call this method from a block passed to the performBatchUpdates:completion: method when you want to animate multiple separate changes into place at the same time. See the description of that method for more information.

**Comment by ide** [comment]
I'm going to test this a little more (specifically around moving rows after having inserted & deleted some) since I believe the combination of all three operations is undocumented.

**Comment by toulouse** [comment]
OK. I'm pretty confident in it, but if you do find bugs, please let me know, and if possible, print out the delta so we can reproduce the same sort of update operations with the examples.

**Comment by ide** [comment]
Looks great. I bumped the row count of the table view to 100 rows and clicked a bunch of times. The displayed rows always matched `_newItems`.

If you message me the email address you use for CocoaPods I can add you as an owner.

**Pull request merged**
